name: Build Kernel Hermes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        ref: lineage-16.0

    - name: Install Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y bc build-essential zip curl libssl-dev libc6-i386 lib32stdc++6 lib32z1 binutils-aarch64-linux-gnu libncurses5 libncurses5:i386 libstdc++6:i386

    - name: Download Toolchain
      run: |
        git clone https://github.com/lineageos/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 toolchain --depth=1

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-android-
        
        make clean
        make mrproper
        make hermes_defconfig
        
        # --- FIX ERROR CGROUP & FS GLOBAL ---
        find fs/ kernel/ -type f -name "*.c" -exec sed -i 's/\([^ ]*\)->euid != \([^ ]*\)->suid/!uid_eq(\1->euid, \2->suid)/g' {} +
        find fs/ kernel/ -type f -name "*.c" -exec sed -i 's/\([^ ]*\)->uid != \([^ ]*\)->uid/!uid_eq(\1->uid, \2->uid)/g' {} +
        find fs/ kernel/ -type f -name "*.c" -exec sed -i 's/\([^ ]*\)->gid != \([^ ]*\)->gid/!gid_eq(\1->gid, \2->gid)/g' {} +

        # --- FIX SPECIFIC SDCARDFS UID/GID ERROR ---
        # Mengubah penetapan langsung menjadi pembungkus KUIDT_INIT
        sed -i 's/attrs.ia_uid = uid/attrs.ia_uid = KUIDT_INIT(uid)/g' fs/sdcardfs/sdcardfs.h
        sed -i 's/attrs.ia_gid = gid/attrs.ia_gid = KGIDT_INIT(gid)/g' fs/sdcardfs/sdcardfs.h
        sed -i 's/dest->i_uid = SDCARDFS_I(dest)->data->d_uid/dest->i_uid = KUIDT_INIT(SDCARDFS_I(dest)->data->d_uid)/g' fs/sdcardfs/sdcardfs.h
        sed -i 's/dest->i_gid = AID_SDCARD_RW/dest->i_gid = KGIDT_INIT(AID_SDCARD_RW)/g' fs/sdcardfs/sdcardfs.h

        # --- SUNTIK NAMESPACE ---
        sed -i 's/# CONFIG_NAMESPACES is not set/CONFIG_NAMESPACES=y/' .config
        {
          echo "CONFIG_UTS_NS=y"
          echo "CONFIG_IPC_NS=y"
          echo "CONFIG_USER_NS=y"
          echo "CONFIG_PID_NS=y"
          echo "CONFIG_NET_NS=y"
        } >> .config
        
        make -j$(nproc)

    - name: Check Output
      run: |
        if [ -f arch/arm64/boot/Image.gz-dtb ]; then
          echo "✅ KERNEL BERHASIL!"
        else
          echo "❌ KERNEL GAGAL!"
          exit 1
        fi

    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Hermes-Update
        path: arch/arm64/boot/Image.gz-dtb
